Bitmap position
go-text/render pull request #17
Opened 2024-04-09 14:25 UTC by benoitkugler

This is an alternative to #16 : using the metric computed in glyph.YBearing.

In `drawBitmap`,  (x, y) are the position of the baseline and `glyph.Height` is not really what we want since its also includes the _descent_. Fortunately, `glyph.YBearing` precisely gives the distance between the baseline and the top of the bitmap content.

I think it should also fix #15.

2024-04-09 14:33 UTC, whereswaldon commented on render_test.go
> +	face, _ := font.ParseTTF(bytes.NewReader(data))
This rasterizes, but doesn't test for correctness. Shouldn't we compare it against the checked-in reference image to ensure we don't break the alignment in the future?

2024-04-09 16:14 UTC, benoitkugler commented on render_test.go
> +	face, _ := font.ParseTTF(bytes.NewReader(data))
Nice suggestion, done !

2024-04-09 16:30 UTC, andydotxyz approved these changes
Fantastic, much better solution thanks.

2024-04-09 16:37 UTC, andydotxyz requested changes

2024-04-09 16:37 UTC, andydotxyz commented on bitmap.go
> +		rect := image.Rect(int(x), int(y-fixed266ToFloat(g.YBearing)*r.PixScale), int(x+fixed266ToFloat(g.Width)*r.PixScale), int(y))
The aspect ratio looks wrong - should `g.Width` be `g.XBearing` so we are using the same coordinate on both directions?

2024-04-09 16:37 UTC, andydotxyz commented
More testing showed a flaw, the faces should be circle

2024-04-09 16:39 UTC, andydotxyz commented on bitmap.go
> +		rect := image.Rect(int(x), int(y-fixed266ToFloat(g.YBearing)*r.PixScale), int(x+fixed266ToFloat(g.Width)*r.PixScale), int(y))
Oops, it isn't that simple sorry. But I think it needs to know the ratio of height to YBearing and then apply that to the X axis

2024-04-09 18:11 UTC, benoitkugler commented
> More testing showed a flaw, the faces should be circle

Ah nice catch ! From the top, we should go down to the end of the glyph, not just to the baseline. Fixed in  [e83f694](https://github.com/go-text/render/pull/17/commits/e83f694b71574a0f5dc8b8249022d1cad137eb14)

2024-04-10 08:39 UTC, andydotxyz approved these changes
Excellent thanks so much!

2024-04-10 16:01 UTC, merged